### ISSUE TITLE
关于【查询结果如何突破最大 1000 条的限制】的疑问

### ISSUE THREAD

**Issue by GongT** [leancloud/knowhow#1]
现在我用的是第一次 skip(0) limit(1000) 第二次 skip(1000) limit(1000) 以此类推 的方法查询的

这样做和这里建议的方法有什么区别？

**Comment by BinaryHB** [comment]
@GongT 你好，这里的处理办法是为了超出 1000 条。skip() 用来分页，一般都是 10，比较好。但如果你直接 skip(10000) 就会比较慢了，不推荐那么做。
