### ISSUE TITLE
第三方登录的 user/get_simple_userinfo 回调重复

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/knowhow#12]
详见：https://forum.leancloud.cn/t/qq-callback/13401

**Comment by BinaryHB** [comment]
关联：https://github.com/leancloud/android-sdk/issues/752

**Comment by okadaNana** [comment]
Tencent.onActivityResultData() 这个方法不能在 Activity.onActivityResult() 里调用两次，否则就会出现这个问题

**Comment by Apples0609** [comment]
@okadaNana 调两次？我只是按文档，重新Activity的onActivityResult，然后
SNS.onActivityResult(requestCode, resultCode, data, type);
若是真有调两次，那也是你们sdk返回有问题，调了两次！
