### ISSUE TITLE
Android _Installation問題

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/knowhow#8]
详见：https://forum.leancloud.cn/t/android--installation/5756

**Comment by BinaryHB** [comment]
关联：https://github.com/leancloud/android-sdk/issues/720

**Comment by hzw1199** [comment]
遇到一样的问题了，求解决

**Comment by BinaryHB** [comment]
正在 fix 中，请稍等。

**Comment by BinaryHB** [comment]
已修复。
